import pandas as pd

if __name__ == "__main__":
    data = pd.read_csv("data/CRDC2013_14.csv", encoding="Latin-1")
    data["total_enrollment"] = data["TOT_ENR_M"] + data["TOT_ENR_F"]
    all_enrollment = sum(data["total_enrollment"])
    hisp_male = sum(data["SCH_ENR_HI_M"])
    hisp_female = sum(data["SCH_ENR_HI_F"])
    am_ind_m = sum(data["SCH_ENR_AM_M"])
    am_ind_f = sum(data["SCH_ENR_AM_F"])
    asian_m = sum(data["SCH_ENR_AS_M"])
    asian_f = sum(data["SCH_ENR_AS_F"])
    hawa_pi_m = sum(data["SCH_ENR_HP_M"])
    hawa_pi_f = sum(data["SCH_ENR_HP_F"])
    bl_m = sum(data["SCH_ENR_BL_M"])
    bl_f = sum(data["SCH_ENR_BL_F"])
    wh_m = sum(data["SCH_ENR_WH_M"])
    wh_f = sum(data["SCH_ENR_WH_F"])
    two_more_m = sum(data["SCH_ENR_TR_M"])
    two_more_f = sum(data["SCH_ENR_TR_F"])

    hispanic_female = "Hispanic Female: " + str(hisp_female/all_enrollment)
    hispanic_male = "Hispanic Male: " + str(hisp_male/all_enrollment)
    american_indian_male = "American Indian Male: " + str(am_ind_m/all_enrollment)
    american_indian_female = "American Indian Female: " + str(am_ind_f/all_enrollment)
    asian_male = "Asian Male: " + str(asian_m/all_enrollment)
    asian_female = "Asian Female: " + str(asian_f/all_enrollment)
    hawaiin_pacific_islander_male = "Hawiian or Pacific Islander Male: " + str(hawa_pi_m/all_enrollment)
    hawaiin_pacific_islander_female = "Hawiian or Pacific Islander Female: " + str(hawa_pi_f/all_enrollment)
    black_male = "Black Male: " + str(bl_m/all_enrollment)
    black_female = "Black Female: " + str(bl_f/all_enrollment)
    white_male = "White Male: " + str(wh_m/all_enrollment)
    white_female = "White Female: " + str(wh_f/all_enrollment)
    two_or_more_races_male = "Two or more races Male: " + str(two_more_m/all_enrollment)
    two_or_more_races_female = "Two or more races Female: " + str(two_more_f/all_enrollment)
    # print (hispanic_male)
    # print (hispanic_female)
    # print (american_indian_male)
    # print (american_indian_female)
    # print (hawaiin_pacific_islander_male)
    # print (hawaiin_pacific_islander_female)
    # print (black_male)
    # print (black_female)
    # print (white_male)
    # print (white_female)
    # print (two_or_more_races_male)
    # print (two_or_more_races_female)
